global using DomainSeedWork;
global using DomainSeedWork.Abstractions;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using System;
global using System.Collections.Generic;
global using TagS.Core.Models;
global using TagS.Microservices.Client.DomainSeedWork;
global using TagS.Microservices.Client.Models;
