global using DomainSeedWork;
global using DomainSeedWork.Abstractions;
global using Innermost.Meet.Domain.AggregatesModels.SharedLifeRecordAggregate;
global using Innermost.Meet.Domain.Repositories;
global using MongoDB.Driver;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
