global using DomainSeedWork;
global using DomainSeedWork.Abstractions;
global using Innermost.MusicHub.Domain.Repositories;
global using MongoDB.Driver;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using Innermost.MongoDBContext;
global using Innermost.MongoDBContext.Configurations;
